import crypto from "node:crypto";

function scalar(value) {
  if (value === null) return "null";
  if (typeof value === "boolean" || typeof value === "number") return String(value);
  const text = String(value);
  if (/^[A-Za-z0-9_./-]+$/.test(text)) return text;
  return JSON.stringify(text);
}

export function toYaml(value, indent = 0) {
  const padding = " ".repeat(indent);
  if (Array.isArray(value)) {
    if (value.length === 0) return "[]";
    return value.map((item) => {
      if (item && typeof item === "object") {
        const rendered = toYaml(item, indent + 2);
        return `${padding}-\n${rendered}`;
      }
      return `${padding}- ${scalar(item)}`;
    }).join("\n");
  }
  if (value && typeof value === "object") {
    const entries = Object.entries(value);
    if (entries.length === 0) return "{}";
    return entries.map(([key, child]) => {
      if (child && typeof child === "object") return `${padding}${key}:\n${toYaml(child, indent + 2)}`;
      return `${padding}${key}: ${scalar(child)}`;
    }).join("\n");
  }
  return `${padding}${scalar(value)}`;
}

export function stableStringify(value) {
  if (Array.isArray(value)) return `[${value.map(stableStringify).join(",")}]`;
  if (value && typeof value === "object") {
    return `{${Object.keys(value).sort().map((key) => `${JSON.stringify(key)}:${stableStringify(value[key])}`).join(",")}}`;
  }
  return JSON.stringify(value);
}

export function digest(value) {
  return crypto.createHash("sha256").update(typeof value === "string" ? value : stableStringify(value)).digest("hex");
}

function generatedHeader(hash) {
  return `<!-- GENERATED BY @prismtek/buap-compiler; source-sha256=${hash}; DO NOT EDIT -->`;
}

export function renderMarkdown({ title, sections, hash }) {
  const body = sections
    .sort((a, b) => (a.order ?? 0) - (b.order ?? 0) || a.id.localeCompare(b.id))
    .map((section) => `## ${section.title}\n\n${section.body.trim()}`)
    .join("\n\n");
  return `${generatedHeader(hash)}\n# ${title}\n\n${body}\n`;
}

export function renderYaml(value, hash) {
  return `# GENERATED BY @prismtek/buap-compiler; source-sha256=${hash}; DO NOT EDIT\n${toYaml(value)}\n`;
}
